CREATE DATABASE EXAMEN2
GO

USE EXAMEN2
GO

CREATE TABLE USUARIOS
(
	UsuarioID int identity(1,1),
	Nombre NVARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Telefono VARCHAR(15) NULL,
	CONSTRAINT pk_UsuarioID PRIMARY KEY(UsuarioID)
)
GO

CREATE TABLE TECNICOS
(
	TecnicoID int identity(1,1),
	Nombre VARCHAR(50),
	Especialidad VARCHAR(50),
	CONSTRAINT pk_TecnicoID PRIMARY KEY(TecnicoID)
)
GO

CREATE TABLE EQUIPOS
(
	EquipoID int identity(1,1),
	TipoEquipo NVARCHAR(50) NOT NULL,
	Modelo VARCHAR(50) NOT NULL,
	UsuarioID INT,
	CONSTRAINT pk_EquipoID PRIMARY KEY(EquipoID),
	CONSTRAINT fk_UsuarioID FOREIGN KEY (UsuarioID) REFERENCES USUARIOS(UsuarioID)
)
GO

CREATE TABLE REPARACIONES
(
	ReparacionID int identity(1,1),
	EquipoID int,
	FechaSolicitud datetime CONSTRAINT df_fechaSoli DEFAULT GETDATE(),
	Estado varchar(50) NOT NULL,
	CONSTRAINT pk_ReparacionId PRIMARY KEY(ReparacionId),
	CONSTRAINT fk_EquipoID FOREIGN KEY (EquipoID) REFERENCES EQUIPOS(EquipoID)
)
GO

CREATE TABLE DETALLESREPARACION
(
	DetalleID int identity(1,1),
	ReparacionID int,
	Descripcion VARCHAR(50),
	FechaInicio datetime CONSTRAINT df_fechaIni DEFAULT GETDATE(),
	FechaFin datetime CONSTRAINT df_fechaFin DEFAULT GETDATE()
	CONSTRAINT pk_DetalleID PRIMARY KEY(DetalleID),
	CONSTRAINT fk_ReparacionID FOREIGN KEY (ReparacionID) REFERENCES REPARACIONES(ReparacionID)
)
GO

CREATE TABLE ASIGNACIONES
(
	AsignacionID int identity(1,1),
	ReparacionID int,
	TecnicoID int,
	FechaAsignacion datetime CONSTRAINT df_fechaAsig DEFAULT GETDATE(),
	CONSTRAINT pk_AsignacionID PRIMARY KEY(AsignacionID),
	CONSTRAINT fk_Reparacion FOREIGN KEY (ReparacionID) REFERENCES REPARACIONES(ReparacionID),
	CONSTRAINT fk_TecnicoID FOREIGN KEY (TecnicoID) REFERENCES TECNICOS(TecnicoID)
)
GO

INSERT INTO Usuarios(Nombre, Email, Telefono) VALUES 
('Josue Caleb', 'jcaleb@gmail.com', '8336-9665'), 
('Ana Lucia', 'analu@gmail.com', '2444-5102'), 
('Carlos Eduardo', 'carled@gmail.com', '2476-1963'),
('Jorge Murillo', 'jmurillo@gmail.com', '9669-0002')
GO

INSERT INTO Tecnicos(Nombre, Especialidad) VALUES 
('Misael', 'Laptop'), 
('Erick', 'Pantallas'),
('Daniel', 'Tecldos y mouse')
GO

INSERT INTO Equipos(TipoEquipo, Modelo, UsuarioID) VALUES
('Laptop', 'Lenovo', 1),
('Mouse ', 'Logitech', 2),
('Teclado', 'x-Tech', 3),
('Monitor', 'Asus', 4)

GO






CREATE PROCEDURE CONSULTAR_USUARIOS
AS
	BEGIN
		SELECT * FROM USUARIOS
	END
GO

CREATE PROCEDURE CONSULTAR_USUARIOS_ID
@ID_US INT
AS
	BEGIN
		SELECT * FROM USUARIOS WHERE UsuarioID = @ID_US
	END
GO

CREATE PROCEDURE BORRAR_USU_ID
@ID_US INT
AS
	BEGIN
		DELETE USUARIOS WHERE UsuarioID = @ID_US
	END
GO

CREATE PROCEDURE INSERTAR_USUARIO
@Nombre VARCHAR(50),
@Email VARCHAR(50),
@Telefono VARCHAR(50)
AS
	BEGIN
		INSERT INTO USUARIOS (Nombre, Email,Telefono) VALUES (@Nombre, @Email, @Telefono)
	END
GO

CREATE PROCEDURE ACTUALIZAR
@ID_USU INT,
@Nombre VARCHAR(50),
@Email VARCHAR(50),
@Telefono VARCHAR(50)
AS
	BEGIN
		UPDATE USUARIOS SET Nombre = @Nombre WHERE UsuarioID=@ID_USU
		UPDATE USUARIOS SET Email = @Email WHERE UsuarioID=@ID_USU
		UPDATE USUARIOS SET Telefono = @Telefono WHERE UsuarioID=@ID_USU
	END
GO

CREATE PROCEDURE CONSULTAR_TECNICOS
AS
	BEGIN
		SELECT * FROM TECNICOS
	END
GO

CREATE PROCEDURE CONSULTAR_TECNICOS_ID
@ID_TEC INT
AS
	BEGIN
		SELECT * FROM TECNICOS WHERE TecnicoID = @ID_TEC
	END
GO

CREATE PROCEDURE BORRAR_TEC_ID
@ID_TEC INT
AS
	BEGIN
		DELETE TECNICOS WHERE TecnicoID = @ID_TEC
	END
GO

CREATE PROCEDURE INSERTAR_TEC
@Nombre VARCHAR(50),
@Especialidad VARCHAR(50)
AS
	BEGIN
		INSERT INTO TECNICOS (Nombre, Especialidad) VALUES (@Nombre, @Especialidad)
	END
GO

CREATE PROCEDURE ACTUALIZAR_TEC_ID
@ID_TEC INT,
@Nombre VARCHAR(50),
@Especialidad VARCHAR(50)
AS
	BEGIN
		UPDATE TECNICOS SET Nombre = @Nombre, Especialidad = @Especialidad WHERE TecnicoID=@ID_TEC
	END
GO

CREATE PROCEDURE CONSULTAR_EQUIPOS
AS
	BEGIN
		SELECT * FROM EQUIPOS
	END
GO

CREATE PROCEDURE CONSULTAR_EQUIPOS_ID
@ID_EQUIP INT
AS
	BEGIN
		SELECT *FROM EQUIPOS WHERE EquipoID = @ID_EQUIP
	END
GO

CREATE PROCEDURE BORRAR_EQUIPOS
@ID_EQUIP INT
AS
	BEGIN
		DELETE EQUIPOS WHERE EquipoID = @ID_EQUIP
	END
GO

CREATE PROCEDURE INSERTAR_EQUIPOS
@TIPO_EQUIP VARCHAR(50),
@MODELO VARCHAR(50),
@USUARIO INT
AS
	BEGIN
		INSERT INTO EQUIPOS(TipoEquipo, Modelo, UsuarioID) VALUES (@TIPO_EQUIP, @MODELO, @USUARIO)
	END
GO

CREATE PROCEDURE ACTUALIZAR_EQUIP_ID
@ID_EQUIP INT,
@TIPO_EQUIP VARCHAR(50),
@MODELO VARCHAR(50),
@USUARIO VARCHAR(50)
AS
	BEGIN
		UPDATE EQUIPOS SET TipoEquipo = @TIPO_EQUIP WHERE EquipoID=@ID_EQUIP
		UPDATE EQUIPOS SET Modelo = @MODELO WHERE EquipoID=@ID_EQUIP
		UPDATE EQUIPOS SET UsuarioID = @USUARIO WHERE EquipoID=@ID_EQUIP
	END
GO 